//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monzon.BL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public int UNIQUE_ID { get; set; }
        public string LOGIN1 { get; set; }
        public string PASSWORD { get; set; }
        public bool ACTIVE { get; set; }
        public int ID_PROFILE { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string EUID_HASH { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
        public bool HIVE { get; set; }
    
        public virtual PROFILE PROFILE { get; set; }
    }
}
