//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monzon.BL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLACE
    {
        public int UNIQUE_ID { get; set; }
        public string NAME { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public string SUBTITLE { get; set; }
        public bool DELETED { get; set; }
        public int PLACE_TYPE_ID { get; set; }
    
        public virtual PLACE_TYPE PLACE_TYPE { get; set; }
    }
}
