//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monzon.BL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        public int UNIQUE_ID { get; set; }
        public string TITLE { get; set; }
        public string URL { get; set; }
        public string TEXT { get; set; }
        public System.DateTime POST_DATE { get; set; }
    }
}
