//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monzon.BL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFILE
    {
        public int UNIQUE_ID { get; set; }
        public string CAPTION { get; set; }
        public bool ACTIVE { get; set; }
        public string BIZ_ID { get; set; }
    }
}
